### ISSUE TITLE
When are snapshots created or changed for local repos?

### ISSUE THREAD

**Issue by daledude** [lbr38/repomanager#189]
Thank you for this interesting project! 

I'm creating a local deb/rpm repo and am wondering when the snapshot will be updated. I assume the first snapshot is created on repo creation. But, I don't see the snapshot change on package upload/delete. Is the snapshot mostly for mirroring? Sorry, bit confused on snapshot usage.

**Comment by lbr38** [comment]
Hello,

Yes, snapshots are primarily used by mirrors. Local repos came later and were not designed for their snapshots to be updated. They are "static" repos.

I cannot allow updating snapshots during a package upload/deletion because it requires a complete copy of the previous snapshot, which could take too much time if the snapshot contains several gigabytes of data.

However, I could consider a solution to update the snapshots of local repos.

**Comment by daledude** [comment]
Thank you. So local repo I dont need to worry about rhe snapshot changing.

**Comment by lbr38** [comment]
`4.20.0` now provides a way to create new snapshots for local repositories
